### ISSUE TITLE
New open source search engine

### ISSUE THREAD

**Issue by Mat-moran** [OCA/search-engine#108]
**Is your feature request related to a problem?**
NO

**Additional context**
Searching google I found this search engine.

I am already using algolia because it is very simple to use and they have a very great admin experience, but this seem very nice search engine too an is open source.

Just to let you know this one.

https://typesense.org/

**Comment by PierrickBrun** [comment]
I think that would be great too.

Also, just for the record there is also https://www.meilisearch.com/ that can be used.

But if there is a new implementation to add, I'd go with typesense first

**Comment by JuanDCG314** [comment]
I'm working with [OpenDistroForElasticsearch](https://github.com/opendistro-for-elasticsearch), that is the original fork of Elastic Stack. But now it is becoming to end of life, so we've [OpenSearch](https://github.com/opensearch-project).

What is your opinion about these?

**Comment by bealdav** [comment]
Fresh comparison between solutions

https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#general-overview
