### ISSUE TITLE
[RFC] get rid of SE specific backend

### ISSUE THREAD

**Issue by hparfr** [OCA/search-engine#111]
**Is your feature request related to a problem?**

search engine object inheritence is too complex and not aligned with other practices we have in oca.
It's the root of some bugs, provide a bad UX, and high barrier entry for new commers.

**Describe the solution you'd like**
I suggest to remove `se_backend_spec_abstract`, `se.backend.algolia`, `se.backend.elastic`.  Do a simplist implementation with prefixed fields on `se.backend`
Like: `elastic_server_host `, `algolia_app_id`...

**Describe alternatives you've considered**

Alternative implementation can be found on oca/storage with sparse_fields.

**Additional context**

In all our (Akretion) implementations we do not have both modules installed on the same time. 
But even if it's the case (algolia and elastic installed altogether), having two or more columns on connector_search_engine views should not be something we should worried at. These kind of settings are not modified often.

**Comment by hparfr** [comment]
ping @sebastienbeau @simahawk @lmignon

**Comment by lmignon** [comment]
@hparfr I agree, the approach is quite complex. Nevertheless, the initial motivation is to avoid extension by inheritance and replace it with extension by composition. This allows to avoid mixing apple and orange stuff into the same model. (Algolia is not ES).

**Comment by sebastienbeau** [comment]
@lmignon @sbidoul @simahawk We should talk about this during the code sprint

**Comment by sebastienbeau** [comment]
Note on V14: due to inherit mecanisme the server-env config is still broken see following PR: https://github.com/OCA/search-engine/pull/79

**Comment by sebastienbeau** [comment]
Let's do it !

**Comment by simahawk** [comment]
Is anyone taking care of this already? Otherwise I could take it.

**Comment by hparfr** [comment]
You can take it. Thanks @simahawk

**Comment by sebastienbeau** [comment]
This have been done here : https://github.com/OCA/search-engine/commit/53b9096c8233f80d1aab4ceebc77f233af769015
