### ISSUE TITLE
[12] How to configure eslastic search on Odoo V.12? Help me!

### ISSUE THREAD

**Issue by nguyentrong6193** [OCA/search-engine#40]
Hi Bros,
I have installed the ES Module on Odoo V.12. 
How to configure eslastic search on Odoo V.12? Help me, Please !

**Comment by hparfr** [comment]
Hi,

Currently you can find only base modules for search engines. 

There is not so much implementations yet. You can find one in shopinvader repository
https://github.com/shopinvader/odoo-shopinvader/tree/12.0/shopinvader_elasticsearch

**Comment by luffah** [comment]
@nguyentrong6193 did you success to use the connector with the exemple of of shopinvader ?
