### ISSUE TITLE
Documentation of connector_elasticsearch?

### ISSUE THREAD

**Issue by CakJuice** [OCA/search-engine#44]
Is there any documentation about how to use connector_elasticsearch module?
Thank you.

**Comment by hparfr** [comment]
There is no documentation yet.

You can have a look to these implementations:
https://github.com/shopinvader/odoo-shopinvader/tree/12.0/shopinvader_elasticsearch
https://github.com/shopinvader/odoo-shopinvader/tree/12.0/shopinvader_search_engine
