### ISSUE TITLE
Support for odoo server version 11

### ISSUE THREAD

**Issue by chitswe** [OCA/search-engine#61]
Which branch should I use for odoo server version 11?

**Comment by lmignon** [comment]
Hi @chitswe. Unfortunately these addons are not (yet) available for odoo 11. If you need these addons for Odoo 11, you have to migrate them from Odoo 12 or 13. The migration steps are described here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0 but must be adapted to the current context.
Regards
