### ISSUE TITLE
Install on Odoo14 failed

### ISSUE THREAD

**Issue by MBadberg** [OCA/search-engine#92]
Command pip install odoo14-addon-connector-search-engine

Error Message:
Collecting odoo14-addon-connector-search-engine
  Downloading odoo14_addon_connector_search_engine-14.0.1.2.0-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 5.5 MB/s
Collecting odoo14-addon-server-environment
  Downloading odoo14_addon_server_environment-14.0.1.0.1.dev5-py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB 14.0 MB/s
Collecting odoo14-addon-connector
  Using cached odoo14_addon_connector-14.0.1.0.1.dev3-py3-none-any.whl (756 kB)
ERROR: Could not find a version that satisfies the requirement odoo<14.1dev,>=14.0a (from odoo14-addon-connector-search-engine) (from versions: none)
ERROR: No matching distribution found for odoo<14.1dev,>=14.0a (from odoo14-addon-connector-search-engine)

**Comment by rousseldenis** [comment]
@MBadberg You don't have an Odoo 14.0 installed in your environment. That cause the problem (check it with 'pip list')
